# -*- coding: utf-8 -*-
"""ScrapingFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGbsOTSgaUSuvraGF5_YRUfBfTMhKm8T
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-colab-selenium

import google_colab_selenium as webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd
import csv

link="https://www.ft.com/search?q=Microsoft"
options = Options()
driver = webdriver.Chrome(options=options)

import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from datetime import datetime

dataset = []

for i in range(2, 5):
    driver.get(link)
    wait = WebDriverWait(driver, 10)

    # Gestione banner cookie
    try:
        iframe = wait.until(EC.presence_of_element_located((By.ID, "sp_message_iframe_1349677")))
        driver.switch_to.frame(iframe)
        accept_button = wait.until(EC.element_to_be_clickable(
            (By.CSS_SELECTOR, "button[title='Accept'], button[aria-label='Accept']")))
        accept_button.click()
        driver.switch_to.default_content()
    except Exception:
        pass

    lista = driver.find_elements(By.CLASS_NAME, "search-results__list-item")

    for index, titolo in enumerate(lista, start=1+(i-1)*len(lista)):
        try:
            link_element = titolo.find_element(By.CLASS_NAME, "js-teaser-heading-link")
            url_articolo = link_element.get_attribute("href")
            testo = link_element.text

            riassunto_element = titolo.find_element(By.CLASS_NAME, "js-teaser-standfirst-link")
            riassunto = riassunto_element.text

            # --- Estrazione data e ora in formato europeo ---
            try:
                time_element = titolo.find_element(By.CLASS_NAME, "o-teaser__timestamp-date")
                datetime_attr = time_element.get_attribute("datetime")  # es. "2025-08-07T23:39:28+0000"
                dt = datetime.strptime(datetime_attr, "%Y-%m-%dT%H:%M:%S%z")
                data = dt.strftime("%Y-%m-%d")
                ora = dt.strftime("%H:%M:%S")
            except Exception:
                data = ""
                ora = ""

            dataset.append({
                "Index": index,
                "Titolo": testo,
                "Link": url_articolo,
                "Riassunto": riassunto,
                "Data": data,
                "Ora": ora
            })

        except Exception as e_inner:
            print(f"Errore elemento {index}: {e_inner}")

# Chiudi driver
driver.quit()

# Salva in DataFrame pandas
df = pd.DataFrame(dataset)
print(df)

import os
from huggingface_hub import login

login(token=os.environ["HF_TOKEN"])

from datasets import load_dataset, Dataset
import pandas as pd

repo_id = "SelmaNajih001/FT_Microsoft"


try:
    old = load_dataset(repo_id, split="train")
    old_df = old.to_pandas()
except:
    old_df = pd.DataFrame()

# Unisci vecchi + nuovi (evita duplicati su Titolo+Data)
all_df = pd.concat([old_df, df]).drop_duplicates(subset=["Titolo", "Data"], keep="last")

# ✅ ulteriore check finale
all_df = all_df.drop_duplicates(subset=["Titolo", "Data"], keep="last").reset_index(drop=True)

# Crea nuovo dataset
final_ds = Dataset.from_pandas(all_df)

# Pubblica aggiornato
final_ds.push_to_hub(repo_id, private=False)
